// @ts-check
/**
 * Generates src/environments/environment.prod.ts from OS / CI environment variables.
 *
 * Usage (before `ng build --configuration production`):
 *   node scripts/set-env.js
 *
 * Environment variables (all optional — defaults match the dev environment):
 *
 *   NG_API_URL              REST API base path           default: /api
 *   NG_WS_URL               WebSocket endpoint URL       default: wss://localhost:3000/ws
 *   NG_APP_NAME             Application display name     default: DisposaMail
 *   NG_APP_TAGLINE          Marketing tagline            default: Temporary Email, Zero Hassle
 *   NG_APP_URL              Canonical URL of the app     default: https://localhost:4200
 *   NG_GA_TRACKING_ID       Google Analytics 4 ID        default: (empty — GA disabled)
 *   NG_ADSENSE_PUBLISHER_ID Google AdSense publisher ID  default: (empty — ads disabled)
 *   NG_ADSENSE_SLOT_ID      Google AdSense slot ID       default: (empty — ads disabled)
 *   NG_STORAGE_PREFIX       localStorage key prefix      default: disposaMail_
 *   NG_APP_VERSION          App version shown in footer  default: dev
 *                           For release builds use the format: <branch-version>.<run-number>
 *                           e.g. 1.0.0.42 for release/1.0.0 branch, run 42
 */

'use strict';

const fs = require('fs');
const path = require('path');

// Load .env for local development convenience; OS/CI env vars still win.
const dotenvPath = path.resolve(__dirname, '../.env');
if (fs.existsSync(dotenvPath)) {
  const dotenvContent = fs.readFileSync(dotenvPath, 'utf8');
  const dotenvLines = dotenvContent.split(/\r?\n/);

  for (const rawLine of dotenvLines) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }

    const separatorIndex = line.indexOf('=');
    if (separatorIndex <= 0) {
      continue;
    }

    const key = line.slice(0, separatorIndex).trim();
    if (!key) {
      continue;
    }

    let value = line.slice(separatorIndex + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    if (process.env[key] === undefined) {
      process.env[key] = value;
    }
  }
}

const targetPath = path.resolve(__dirname, '../src/environments/environment.prod.ts');
const cliArgs = new Set(process.argv.slice(2));
const shouldPatchBuiltHtml = cliArgs.has('--patch-built-html');

/** Read a string env var, falling back to a default value. */
function env(name, defaultValue) {
  const value = process.env[name];
  return value !== undefined && value !== '' ? value : defaultValue;
}

/**
 * Escape a value so it is safe to embed inside a single-quoted TypeScript
 * string literal.  Prevents code injection via crafted env-var values.
 */
function escapeForSingleQuotedString(value) {
  return value
    .replace(/\\/g, '\\\\')   // backslash first
    .replace(/'/g, "\\'")      // single quote
    .replace(/\r/g, '\\r')     // carriage return
    .replace(/\n/g, '\\n')     // newline
    .replace(/\0/g, '\\0');    // null byte
}

// Helper: resolve then escape each value.
const s = (name, defaultValue) => escapeForSingleQuotedString(env(name, defaultValue));

const content = `// THIS FILE IS AUTO-GENERATED by scripts/set-env.js — DO NOT EDIT MANUALLY.
// It is regenerated from environment variables on every production build.
export const environment = {
  production: true,
  apiUrl: '${s('NG_API_URL', '/api')}',
  wsUrl: '${s('NG_WS_URL', '')}',

  // Branding
  appName: '${s('NG_APP_NAME', 'DisposaMail')}',
  appTagline: '${s('NG_APP_TAGLINE', 'Temporary Email, Zero Hassle')}',
  appUrl: '${s('NG_APP_URL', 'https://localhost:4200')}',

  // Google Analytics 4 (leave empty to disable)
  gaTrackingId: '${s('NG_GA_TRACKING_ID', '')}',

  // Google AdSense (leave empty to disable ads)
  adsensePublisherId: '${s('NG_ADSENSE_PUBLISHER_ID', '')}',
  adsenseSlotId: '${s('NG_ADSENSE_SLOT_ID', '')}',

  // Storage key prefix (for localStorage)
  storagePrefix: '${s('NG_STORAGE_PREFIX', 'disposaMail_')}',

  // App version shown in footer (set to <branch-version>.<run-number> by CI)
  appVersion: '${s('NG_APP_VERSION', 'dev')}',
};
`;

fs.mkdirSync(path.dirname(targetPath), { recursive: true });
fs.writeFileSync(targetPath, content, 'utf8');
console.log(`✅  Generated ${path.relative(process.cwd(), targetPath)}`);

// ─── Generate src/index.prod.html ─────────────────────────────────────────────
// Inject the Google AdSense <script> directly into <head> so it is present in
// the HTML entry point regardless of Angular's JS bundle tree-shaking.
// When NG_ADSENSE_PUBLISHER_ID is unset the placeholder comment is preserved.

/**
 * Normalise a raw publisher-ID value to the canonical `ca-pub-NNNNN` form.
 * Returns an empty string for unrecognised or empty input.
 * @param {string} value
 * @returns {string}
 */
function normalizePublisherId(value) {
  const id = (value || '').trim();
  if (!id) return '';
  if (/^ca-pub-\d+$/.test(id)) return id;
  if (/^pub-\d+$/.test(id)) return `ca-${id}`;
  if (/^\d+$/.test(id)) return `ca-pub-${id}`;
  return '';
}

const rawPublisherId    = env('NG_ADSENSE_PUBLISHER_ID', '');
const normalizedPubId   = normalizePublisherId(rawPublisherId);

// Pattern that matches the commented-out AdSense placeholder in index.html.
// The anchor ensures we only replace a <script> whose src begins with the
// AdSense URL, not any other commented-out script that happens to reference
// pagead2.googlesyndication.com elsewhere in its attributes.
const adsensePlaceholder =
  /<!--\s*<script\s[^>]*\bsrc="https:\/\/pagead2\.googlesyndication\.com\/pagead\/js\/adsbygoogle\.js[^"]*"[^>]*><\/script>\s*-->/;

const adsenseScriptPattern =
  /<script\s[^>]*\bsrc="https:\/\/pagead2\.googlesyndication\.com\/pagead\/js\/adsbygoogle\.js[^"]*"[^>]*><\/script>/;
const headClosePattern = /<\/head>/i;

function createAdsenseScriptTag(publisherId) {
  return `<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${publisherId}" crossorigin="anonymous"></script>`;
}

function injectAdsenseScript(html, publisherId) {
  if (!publisherId) {
    return {
      html,
      changed: false,
      injected: false
    };
  }

  const scriptTag = createAdsenseScriptTag(publisherId);

  if (adsensePlaceholder.test(html)) {
    return {
      html: html.replace(adsensePlaceholder, scriptTag),
      changed: true,
      injected: true
    };
  }

  if (adsenseScriptPattern.test(html)) {
    return {
      html: html.replace(adsenseScriptPattern, scriptTag),
      changed: true,
      injected: true
    };
  }

  if (headClosePattern.test(html)) {
    return {
      html: html.replace(headClosePattern, `  ${scriptTag}\n</head>`),
      changed: true,
      injected: true
    };
  }

  return {
    html,
    changed: false,
    injected: false
  };
}

function patchHtmlFile(filePath, label) {
  if (!fs.existsSync(filePath)) {
    console.log(`ℹ️   Skipped ${label} — file not found`);
    return;
  }

  const originalHtml = fs.readFileSync(filePath, 'utf8');
  const result = injectAdsenseScript(originalHtml, normalizedPubId);

  if (!normalizedPubId) {
    console.log(`ℹ️   NG_ADSENSE_PUBLISHER_ID not set — AdSense script omitted from ${label}`);
    return;
  }

  if (!result.injected) {
    console.warn(`⚠️   Could not inject AdSense script into ${label}`);
    return;
  }

  if (result.changed) {
    fs.writeFileSync(filePath, result.html, 'utf8');
  }

  console.log(`✅  Injected AdSense script into ${label} (publisher: ${normalizedPubId})`);
}

const indexSrcPath  = path.resolve(__dirname, '../src/index.html');
const indexDestPath = path.resolve(__dirname, '../src/index.prod.html');

fs.mkdirSync(path.dirname(indexDestPath), { recursive: true });
fs.copyFileSync(indexSrcPath, indexDestPath);
patchHtmlFile(indexDestPath, 'src/index.prod.html');
console.log(`✅  Generated ${path.relative(process.cwd(), indexDestPath)}`);

if (shouldPatchBuiltHtml) {
  patchHtmlFile(path.resolve(__dirname, '../dist/frontend/index.html'), 'dist/frontend/index.html');
  patchHtmlFile(path.resolve(__dirname, '../dist/frontend/browser/index.html'), 'dist/frontend/browser/index.html');
}
