// @ts-check
/**
 * Generates src/environments/environment.prod.ts from OS / CI environment variables.
 *
 * Usage (before `ng build --configuration production`):
 *   node scripts/set-env.js
 *
 * Environment variables (all optional — defaults match the dev environment):
 *
 *   NG_API_URL              REST API base path           default: /api
 *   NG_WS_URL               WebSocket endpoint URL       default: wss://localhost:3000/ws
 *   NG_APP_NAME             Application display name     default: DisposaMail
 *   NG_APP_TAGLINE          Marketing tagline            default: Temporary Email, Zero Hassle
 *   NG_APP_URL              Canonical URL of the app     default: https://localhost:4200
 *   NG_GA_TRACKING_ID       Google Analytics 4 ID        default: (empty — GA disabled)
 *   NG_ADSENSE_PUBLISHER_ID Google AdSense publisher ID  default: (empty — ads disabled)
 *   NG_ADSENSE_SLOT_ID      Google AdSense slot ID       default: (empty — ads disabled)
 *   NG_STORAGE_PREFIX       localStorage key prefix      default: disposaMail_
 *   NG_APP_VERSION          App version shown in footer  default: dev
 *                           For release builds use the format: <branch-version>.<run-number>
 *                           e.g. 1.0.0.42 for release/1.0.0 branch, run 42
 */

'use strict';

const fs = require('fs');
const path = require('path');

const targetPath = path.resolve(__dirname, '../src/environments/environment.prod.ts');

/** Read a string env var, falling back to a default value. */
function env(name, defaultValue) {
  const value = process.env[name];
  return value !== undefined && value !== '' ? value : defaultValue;
}

/**
 * Escape a value so it is safe to embed inside a single-quoted TypeScript
 * string literal.  Prevents code injection via crafted env-var values.
 */
function escapeForSingleQuotedString(value) {
  return value
    .replace(/\\/g, '\\\\')   // backslash first
    .replace(/'/g, "\\'")      // single quote
    .replace(/\r/g, '\\r')     // carriage return
    .replace(/\n/g, '\\n')     // newline
    .replace(/\0/g, '\\0');    // null byte
}

// Helper: resolve then escape each value.
const s = (name, defaultValue) => escapeForSingleQuotedString(env(name, defaultValue));

const content = `// THIS FILE IS AUTO-GENERATED by scripts/set-env.js — DO NOT EDIT MANUALLY.
// It is regenerated from environment variables on every production build.
export const environment = {
  production: true,
  apiUrl: '${s('NG_API_URL', '/api')}',
  wsUrl: '${s('NG_WS_URL', 'wss://localhost:3000/ws')}',

  // Branding
  appName: '${s('NG_APP_NAME', 'DisposaMail')}',
  appTagline: '${s('NG_APP_TAGLINE', 'Temporary Email, Zero Hassle')}',
  appUrl: '${s('NG_APP_URL', 'https://localhost:4200')}',

  // Google Analytics 4 (leave empty to disable)
  gaTrackingId: '${s('NG_GA_TRACKING_ID', '')}',

  // Google AdSense (leave empty to disable ads)
  adsensePublisherId: '${s('NG_ADSENSE_PUBLISHER_ID', '')}',
  adsenseSlotId: '${s('NG_ADSENSE_SLOT_ID', '')}',

  // Storage key prefix (for localStorage)
  storagePrefix: '${s('NG_STORAGE_PREFIX', 'disposaMail_')}',

  // App version shown in footer (set to <branch-version>.<run-number> by CI)
  appVersion: '${s('NG_APP_VERSION', 'dev')}',
};
`;

fs.mkdirSync(path.dirname(targetPath), { recursive: true });
fs.writeFileSync(targetPath, content, 'utf8');
console.log(`✅  Generated ${path.relative(process.cwd(), targetPath)}`);
